[package]
name = "chimitheque_front"
version = "0.1.0"
edition = "2024"
authors = ["Thomas Bellembois <thomas.bellembois@proton.me>"]
description = "Frontend for Chimithèque"
license = "GPL-3.0"
repository = "https://github.com/tbellembois/chimitheque_front"
homepage = "https://github.com/tbellembois/chimitheque_front"
readme = "README.md"
categories = ["database", "science"]
keywords = ["chemistry", "biology", "database", "management"]
rust-version = "1.94.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.34.2"
egui = "0.34.2"
egui_extras = { version = "0.34.2", features = ["svg"]}
egui-phosphor =  { version = "0.12", features = ["regular", "fill"]}
ehttp = "0.7.1"
log = "0.4.29"
rust-i18n = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.149"
wasm-rs-shared-channel = "0.1.0"

# thbellem
chimitheque_types = { path = "/home/thbellem/workspace/workspace_rust/chimitheque_types" }
egui_select2 = { path = "/home/thbellem/workspace/workspace_rust/egui_select2" }

web-sys = { version = "0.3.94", features = ["Document", "Window", "Element", "HtmlInputElement"]}
wasm-bindgen = "0.2.117"
js-sys = "0.3.94"
image  = { version = "0.25" }
usvg = "0.47.0"
resvg = "0.47.0"
base64 = "0.22.1"

# chimitheque_types = { git = "https://github.com/tbellembois/chimitheque_types.git", branch = "main" }

# [patch."https://github.com/tbellembois/chimitheque_types.git"]
# chimitheque_types = { path = "../chimitheque_types" }

[lib]
crate-type = ["cdylib", "rlib"]

[profile.dev]
debug = false
